import { Surah } from '@/types';

/**
 * Complete list of all 114 Surahs in the Quran with their metadata
 * Total verses: 6,236 (excluding Bismillah)
 */
export const QURAN_SURAHS: Surah[] = [
  { number: 1, name: 'Al-Fatihah', nameArabic: 'الفاتحة', verses: 7, revelationType: 'Meccan' },
  { number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', verses: 286, revelationType: 'Medinan' },
  { number: 3, name: 'Ali \'Imran', nameArabic: 'آل عمران', verses: 200, revelationType: 'Medinan' },
  { number: 4, name: 'An-Nisa', nameArabic: 'النساء', verses: 176, revelationType: 'Medinan' },
  { number: 5, name: 'Al-Ma\'idah', nameArabic: 'المائدة', verses: 120, revelationType: 'Medinan' },
  { number: 6, name: 'Al-An\'am', nameArabic: 'الأنعام', verses: 165, revelationType: 'Meccan' },
  { number: 7, name: 'Al-A\'raf', nameArabic: 'الأعراف', verses: 206, revelationType: 'Meccan' },
  { number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', verses: 75, revelationType: 'Medinan' },
  { number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', verses: 129, revelationType: 'Medinan' },
  { number: 10, name: 'Yunus', nameArabic: 'يونس', verses: 109, revelationType: 'Meccan' },
  { number: 11, name: 'Hud', nameArabic: 'هود', verses: 123, revelationType: 'Meccan' },
  { number: 12, name: 'Yusuf', nameArabic: 'يوسف', verses: 111, revelationType: 'Meccan' },
  { number: 13, name: 'Ar-Ra\'d', nameArabic: 'الرعد', verses: 43, revelationType: 'Medinan' },
  { number: 14, name: 'Ibrahim', nameArabic: 'ابراهيم', verses: 52, revelationType: 'Meccan' },
  { number: 15, name: 'Al-Hijr', nameArabic: 'الحجر', verses: 99, revelationType: 'Meccan' },
  { number: 16, name: 'An-Nahl', nameArabic: 'النحل', verses: 128, revelationType: 'Meccan' },
  { number: 17, name: 'Al-Isra', nameArabic: 'الإسراء', verses: 111, revelationType: 'Meccan' },
  { number: 18, name: 'Al-Kahf', nameArabic: 'الكهف', verses: 110, revelationType: 'Meccan' },
  { number: 19, name: 'Maryam', nameArabic: 'مريم', verses: 98, revelationType: 'Meccan' },
  { number: 20, name: 'Taha', nameArabic: 'طه', verses: 135, revelationType: 'Meccan' },
  { number: 21, name: 'Al-Anbya', nameArabic: 'الأنبياء', verses: 112, revelationType: 'Meccan' },
  { number: 22, name: 'Al-Hajj', nameArabic: 'الحج', verses: 78, revelationType: 'Medinan' },
  { number: 23, name: 'Al-Mu\'minun', nameArabic: 'المؤمنون', verses: 118, revelationType: 'Meccan' },
  { number: 24, name: 'An-Nur', nameArabic: 'النور', verses: 64, revelationType: 'Medinan' },
  { number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان', verses: 77, revelationType: 'Meccan' },
  { number: 26, name: 'Ash-Shu\'ara', nameArabic: 'الشعراء', verses: 227, revelationType: 'Meccan' },
  { number: 27, name: 'An-Naml', nameArabic: 'النمل', verses: 93, revelationType: 'Meccan' },
  { number: 28, name: 'Al-Qasas', nameArabic: 'القصص', verses: 88, revelationType: 'Meccan' },
  { number: 29, name: 'Al-\'Ankabut', nameArabic: 'العنكبوت', verses: 69, revelationType: 'Meccan' },
  { number: 30, name: 'Ar-Rum', nameArabic: 'الروم', verses: 60, revelationType: 'Meccan' },
  { number: 31, name: 'Luqman', nameArabic: 'لقمان', verses: 34, revelationType: 'Meccan' },
  { number: 32, name: 'As-Sajdah', nameArabic: 'السجدة', verses: 30, revelationType: 'Meccan' },
  { number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب', verses: 73, revelationType: 'Medinan' },
  { number: 34, name: 'Saba', nameArabic: 'سبإ', verses: 54, revelationType: 'Meccan' },
  { number: 35, name: 'Fatir', nameArabic: 'فاطر', verses: 45, revelationType: 'Meccan' },
  { number: 36, name: 'Ya-Sin', nameArabic: 'يس', verses: 83, revelationType: 'Meccan' },
  { number: 37, name: 'As-Saffat', nameArabic: 'الصافات', verses: 182, revelationType: 'Meccan' },
  { number: 38, name: 'Sad', nameArabic: 'ص', verses: 88, revelationType: 'Meccan' },
  { number: 39, name: 'Az-Zumar', nameArabic: 'الزمر', verses: 75, revelationType: 'Meccan' },
  { number: 40, name: 'Ghafir', nameArabic: 'غافر', verses: 85, revelationType: 'Meccan' },
  { number: 41, name: 'Fussilat', nameArabic: 'فصلت', verses: 54, revelationType: 'Meccan' },
  { number: 42, name: 'Ash-Shuraa', nameArabic: 'الشورى', verses: 53, revelationType: 'Meccan' },
  { number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف', verses: 89, revelationType: 'Meccan' },
  { number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان', verses: 59, revelationType: 'Meccan' },
  { number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية', verses: 37, revelationType: 'Meccan' },
  { number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف', verses: 35, revelationType: 'Meccan' },
  { number: 47, name: 'Muhammad', nameArabic: 'محمد', verses: 38, revelationType: 'Medinan' },
  { number: 48, name: 'Al-Fath', nameArabic: 'الفتح', verses: 29, revelationType: 'Medinan' },
  { number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات', verses: 18, revelationType: 'Medinan' },
  { number: 50, name: 'Qaf', nameArabic: 'ق', verses: 45, revelationType: 'Meccan' },
  { number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات', verses: 60, revelationType: 'Meccan' },
  { number: 52, name: 'At-Tur', nameArabic: 'الطور', verses: 49, revelationType: 'Meccan' },
  { number: 53, name: 'An-Najm', nameArabic: 'النجم', verses: 62, revelationType: 'Meccan' },
  { number: 54, name: 'Al-Qamar', nameArabic: 'القمر', verses: 55, revelationType: 'Meccan' },
  { number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن', verses: 78, revelationType: 'Medinan' },
  { number: 56, name: 'Al-Waqi\'ah', nameArabic: 'الواقعة', verses: 96, revelationType: 'Meccan' },
  { number: 57, name: 'Al-Hadid', nameArabic: 'الحديد', verses: 29, revelationType: 'Medinan' },
  { number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة', verses: 22, revelationType: 'Medinan' },
  { number: 59, name: 'Al-Hashr', nameArabic: 'الحشر', verses: 24, revelationType: 'Medinan' },
  { number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة', verses: 13, revelationType: 'Medinan' },
  { number: 61, name: 'As-Saf', nameArabic: 'الصف', verses: 14, revelationType: 'Medinan' },
  { number: 62, name: 'Al-Jumu\'ah', nameArabic: 'الجمعة', verses: 11, revelationType: 'Medinan' },
  { number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون', verses: 11, revelationType: 'Medinan' },
  { number: 64, name: 'At-Taghabun', nameArabic: 'التغابن', verses: 18, revelationType: 'Medinan' },
  { number: 65, name: 'At-Talaq', nameArabic: 'الطلاق', verses: 12, revelationType: 'Medinan' },
  { number: 66, name: 'At-Tahrim', nameArabic: 'التحريم', verses: 12, revelationType: 'Medinan' },
  { number: 67, name: 'Al-Mulk', nameArabic: 'الملك', verses: 30, revelationType: 'Meccan' },
  { number: 68, name: 'Al-Qalam', nameArabic: 'القلم', verses: 52, revelationType: 'Meccan' },
  { number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة', verses: 52, revelationType: 'Meccan' },
  { number: 70, name: 'Al-Ma\'arij', nameArabic: 'المعارج', verses: 44, revelationType: 'Meccan' },
  { number: 71, name: 'Nuh', nameArabic: 'نوح', verses: 28, revelationType: 'Meccan' },
  { number: 72, name: 'Al-Jinn', nameArabic: 'الجن', verses: 28, revelationType: 'Meccan' },
  { number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل', verses: 20, revelationType: 'Meccan' },
  { number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر', verses: 56, revelationType: 'Meccan' },
  { number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة', verses: 40, revelationType: 'Meccan' },
  { number: 76, name: 'Al-Insan', nameArabic: 'الانسان', verses: 31, revelationType: 'Medinan' },
  { number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات', verses: 50, revelationType: 'Meccan' },
  { number: 78, name: 'An-Naba', nameArabic: 'النبإ', verses: 40, revelationType: 'Meccan' },
  { number: 79, name: 'An-Nazi\'at', nameArabic: 'النازعات', verses: 46, revelationType: 'Meccan' },
  { number: 80, name: '\'Abasa', nameArabic: 'عبس', verses: 42, revelationType: 'Meccan' },
  { number: 81, name: 'At-Takwir', nameArabic: 'التكوير', verses: 29, revelationType: 'Meccan' },
  { number: 82, name: 'Al-Infitar', nameArabic: 'الإنفطار', verses: 19, revelationType: 'Meccan' },
  { number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين', verses: 36, revelationType: 'Meccan' },
  { number: 84, name: 'Al-Inshiqaq', nameArabic: 'الإنشقاق', verses: 25, revelationType: 'Meccan' },
  { number: 85, name: 'Al-Buruj', nameArabic: 'البروج', verses: 22, revelationType: 'Meccan' },
  { number: 86, name: 'At-Tariq', nameArabic: 'الطارق', verses: 17, revelationType: 'Meccan' },
  { number: 87, name: 'Al-A\'la', nameArabic: 'الأعلى', verses: 19, revelationType: 'Meccan' },
  { number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية', verses: 26, revelationType: 'Meccan' },
  { number: 89, name: 'Al-Fajr', nameArabic: 'الفجر', verses: 30, revelationType: 'Meccan' },
  { number: 90, name: 'Al-Balad', nameArabic: 'البلد', verses: 20, revelationType: 'Meccan' },
  { number: 91, name: 'Ash-Shams', nameArabic: 'الشمس', verses: 15, revelationType: 'Meccan' },
  { number: 92, name: 'Al-Layl', nameArabic: 'الليل', verses: 21, revelationType: 'Meccan' },
  { number: 93, name: 'Ad-Duhaa', nameArabic: 'الضحى', verses: 11, revelationType: 'Meccan' },
  { number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح', verses: 8, revelationType: 'Meccan' },
  { number: 95, name: 'At-Tin', nameArabic: 'التين', verses: 8, revelationType: 'Meccan' },
  { number: 96, name: 'Al-\'Alaq', nameArabic: 'العلق', verses: 19, revelationType: 'Meccan' },
  { number: 97, name: 'Al-Qadr', nameArabic: 'القدر', verses: 5, revelationType: 'Meccan' },
  { number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة', verses: 8, revelationType: 'Medinan' },
  { number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة', verses: 8, revelationType: 'Medinan' },
  { number: 100, name: 'Al-\'Adiyat', nameArabic: 'العاديات', verses: 11, revelationType: 'Meccan' },
  { number: 101, name: 'Al-Qari\'ah', nameArabic: 'القارعة', verses: 11, revelationType: 'Meccan' },
  { number: 102, name: 'At-Takathur', nameArabic: 'التكاثر', verses: 8, revelationType: 'Meccan' },
  { number: 103, name: 'Al-\'Asr', nameArabic: 'العصر', verses: 3, revelationType: 'Meccan' },
  { number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة', verses: 9, revelationType: 'Meccan' },
  { number: 105, name: 'Al-Fil', nameArabic: 'الفيل', verses: 5, revelationType: 'Meccan' },
  { number: 106, name: 'Quraysh', nameArabic: 'قريش', verses: 4, revelationType: 'Meccan' },
  { number: 107, name: 'Al-Ma\'un', nameArabic: 'الماعون', verses: 7, revelationType: 'Meccan' },
  { number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر', verses: 3, revelationType: 'Meccan' },
  { number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون', verses: 6, revelationType: 'Meccan' },
  { number: 110, name: 'An-Nasr', nameArabic: 'النصر', verses: 3, revelationType: 'Medinan' },
  { number: 111, name: 'Al-Masad', nameArabic: 'المسد', verses: 5, revelationType: 'Meccan' },
  { number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص', verses: 4, revelationType: 'Meccan' },
  { number: 113, name: 'Al-Falaq', nameArabic: 'الفلق', verses: 5, revelationType: 'Meccan' },
  { number: 114, name: 'An-Nas', nameArabic: 'الناس', verses: 6, revelationType: 'Meccan' },
];

export const TOTAL_VERSES = 6236;
export const TOTAL_SURAHS = 114;

/**
 * Get Surah by number
 */
export function getSurah(number: number): Surah | undefined {
  return QURAN_SURAHS.find(s => s.number === number);
}

/**
 * Get all Surahs
 */
export function getAllSurahs(): Surah[] {
  return QURAN_SURAHS;
}
